spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gnivcDataBase?currentSchema=info"
    username: postgres
    password: 12345
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver

  application:
    name: "Delete Application"

queryDelSqlParam: ${AGE}
limitDelSqlParam: 1
firstFixedRate: "0 0 * * * *"
secondFixedRate: "0 0 0 * * *"
tableDelSqlParam: tablet
primalKeyColumnDelSqlParam: id
secondColumnDelSqlParam: age
arithmeticSignDelSqlParam: =

logging:
    config: src/main/resources/log4j.xml




