spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gnivcDataBase?currentSchema=info"
    username: postgres
    password: 12345
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver

  application:
    name: "Delete Application"

queryDelSqlParam: ${AGE}
limitDelSqlParam: 1
fixedRateEveryHour: "0 0 * * * *"
everyTwelveHoursOfTheNightRate: "0 0 0 * * *"
tableSqlParam: tablet
primalKeyColumnSqlParam: id
secondColumnSqlParam: age
arithmeticSignSqlParam: =

logging:
    config: src/main/resources/log4j.xml




